logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://dpg-cppd3l2j1k6c73eh5fb0-a:5432/secure_task_manager_database
    username: secure_task_manager_database_user
    password: xRAk4QXapLElBBhoWwSmK6WxXNbbtNDX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST_NAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enabled: true
    protocol: smtp

server:
  port: 8080

rsa:
  privateKey: classpath:certs/private.pem
  publicKey: classpath:certs/public.pem